layout_spectrum: 0.3554193
typography_spectrum: 1
style: the-composer
color:
  saturation: 0.06362387
  lightness: 0
  brandStrength: 0
  brandColors:
    - '#FFFFFF'
    - '#FCB827'
    - '#62BA49'
    - '#E03A3E'
    - '#000000'
  rhythmicContrast: 0.4374764
name: "John's Passions"
